### ISSUE TITLE
eyeD3 ENOENT

### ISSUE THREAD

**Issue by savire001** [AllToMP3/alltomp3-cli#3]
Hey
Maybe you can help me with my error Message

im Using Win8, npm@2.14.12, python 3.5.1, eyeD3 0.7.1

Converting` A Sky Full of Stars - Coldplay
[================================================--] 97% 0.4sevents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn eyeD3 ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

does this msg tell me that exeD3 ist not found?

**Comment by NTag** [comment]
What does it say when you type `eyeD3 --version` in your terminal?

**Comment by savire001** [comment]
hm eyeD3 command could not found althought i followed these 
[instructions](http://www.mail-archive.com/python-list@python.org/msg144153.html)

**Comment by NTag** [comment]
I am not very familiar with Windows, which is not very friendly for a dev usage...

You must use `pip install eyeD3`, so you need `pip` which comes with Python 2.7.11: https://www.python.org/downloads/release/python-2711/

So, install Python via https://www.python.org/ftp/python/2.7.11/python-2.7.11.msi, then do `pip install eyeD3` and try `eyeD3 --version`.
