### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by quoder** [AllToMP3/alltomp3-cli#4]
I'm running alltomp3-cli in Ubuntu 15.10 . Here are the errors which I got while trying to use it:

sudo alltomp3 https://soundcloud.com/overwerk/matter
Converting https://soundcloud.com/overwerk/matter 
[=================================================] 100% 0.0sUnhandled rejection TypeError: Cannot read property 'replace' of undefined
    at simpleName (/usr/lib/node_modules/alltomp3-cli/node_modules/alltomp3/index.js:1505:16)
    at /usr/lib/node_modules/alltomp3-cli/node_modules/alltomp3/index.js:819:103
    at tryCatcher (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:629:18)
    at PromiseArray._resolve (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:565:26)
    at Promise._settlePromise0 (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/alltomp3-cli/node_modules/bluebird/js/release/promise.js:515:17)

**Comment by NTag** [comment]
Should be fixed with https://github.com/AllToMP3/alltomp3/commit/224b4d59fb9975c2871e301961cb71afadd259ca

Update and retry ;) .

**Comment by quoder** [comment]
I tried it once again but now it gives these errors:

alltomp3 alltomp3 https://soundcloud.com/overwerk/matter
Searching alltomp3 https://soundcloud.com/overwerk/matter 
[--------------------------------------------------] 0% 0.0sUnhandled rejection ReferenceError: reject is not defined
    at /usr/lib/node_modules/alltomp3-cli/node_modules/alltomp3/index.js:977:20
    at tryCatcher (/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/usr/lib/node_modules/alltomp3-cli/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback](timers.js:514:5)

**Comment by NTag** [comment]
Ok there is a bug I will fix, **but** your are not using correctly the program. It is only `alltomp3 https://soundcloud.com/overwerk/matter`and not `alltomp3 alltomp3 https://soundcloud.com/overwerk/matter` (you type twice `alltomp3`).
