### ISSUE TITLE
Unhandled Rejection

### ISSUE THREAD

**Issue by nguyend14** [AllToMP3/alltomp3-cli#5]
I've been getting this error every time recently.

Unhandled rejection StatusCodeError: 403 - [object Object]
    at new StatusCodeError (/usr/local/lib/node_modules/alltomp3-cli/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback](/usr/local/lib/node_modules/alltomp3-cli/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/usr/local/lib/node_modules/alltomp3-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/alltomp3-cli/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/alltomp3-cli/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

**Comment by NTag** [comment]
Ok, Echonest closed its public API (http://developer.echonest.com/docs/v4#announcement), so I have to move to another one, like Spotify... Could take some time, I am sorry.

**Comment by NTag** [comment]
Ok, finally I have been able to do a quick fix, so if you reinstall it should work again :)
