### ISSUE TITLE
Null property of file

### ISSUE THREAD

**Issue by nguyend14** [AllToMP3/alltomp3-cli#8]
alltomp3 https://www.youtube.com/watch?v=3BFkSmqhLWk
Searching https://www.youtube.com/watch?v=3BFkSmqhLWk 
[--------------------------------------------------] 0% 0.0s

/usr/local/lib/node_modules/alltomp3-cli/index.js:153
            console.log("File downloaded: " + chalk.bold.yellow(infos.file));
                                                                     ^

TypeError: Cannot read property 'file' of null
    at /usr/local/lib/node_modules/alltomp3-cli/index.js:153:70
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/alltomp3-cli/node_modules/alltomp3/index.js:917:9)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/alltomp3-cli/node_modules/alltomp3/index.js:403:25)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Readable.<anonymous> (/usr/local/lib/node_modules/alltomp3-cli/node_modules/alltomp3/index.js:258:25)
    at emitOne (events.js:77:13)
    at Readable.emit (events.js:169:7)
    at getInfo (/usr/local/lib/node_modules/alltomp3-cli/node_modules/youtube-dl/lib/youtube-dl.js:106:30)
    at done (/usr/local/lib/node_modules/alltomp3-cli/node_modules/youtube-dl/lib/youtube-dl.js:275:23)
    at done (/usr/local/lib/node_modules/alltomp3-cli/node_modules/youtube-dl/lib/youtube-dl.js:164:31)
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by NTag** [comment]
It works for me :/ .

Could you try to upgrade NodeJS to v7, `rm -rf node_modules`, `npm install -g` and try again?

**Comment by nguyend14** [comment]
on Mac
rm -rf /usr/local/lib/node_modules

To install node version manager:
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash

To list versions:
nvm ls-remote

To install v7.2.1:
nvm install 7.2.1

cd path/to/alltomp3-cli-master 
npm install -g

Thanks!

**Comment by NTag** [comment]
Does it work now for you?

**Comment by nguyend14** [comment]
Yes thanks
