### ISSUE TITLE
Error after converting

### ISSUE THREAD

**Issue by uber1geek** [AllToMP3/alltomp3-cli#9]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn fpcalc ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by NTag** [comment]
I think you didn't install **node-acoustid** requirements: https://github.com/parshap/node-acoustid#installation.

**Comment by uber1geek** [comment]
I have installed it but I am still facing this.

**Comment by NTag** [comment]
So, can you execute `fpcalc` in your command line?

**Comment by Derkades** [comment]
Same issue, installed acoustid and the apt package. Executing `fpcalc` gives the following output:
```
usage: fpcalc [OPTIONS] FILE...

Options:
  -version      print version information
  -length SECS  length of the audio data used for fingerprint calculation (default 120)
  -raw          output the raw uncompressed fingerprint
  -algo NAME    version of the fingerprint algorithm
  -hash         calculate also the fingerprint hash
```

Error (slightly different):
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn eyeD3 ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

UPDATE: Nevermind, seems to be related to #3 
UPDATE 2: Yes, fixed
